// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	brand "shoe-store/domains/brand"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Find provides a mock function with given fields: ctx, active
func (_m *Repository) Find(ctx context.Context, active string) ([]brand.Domain, error) {
	ret := _m.Called(ctx, active)

	var r0 []brand.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string) []brand.Domain); ok {
		r0 = rf(ctx, active)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]brand.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, active)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *Repository) FindByID(id int) (brand.Domain, error) {
	ret := _m.Called(id)

	var r0 brand.Domain
	if rf, ok := ret.Get(0).(func(int) brand.Domain); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(brand.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: ctx, brandName
func (_m *Repository) GetByName(ctx context.Context, brandName string) (brand.Domain, error) {
	ret := _m.Called(ctx, brandName)

	var r0 brand.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string) brand.Domain); ok {
		r0 = rf(ctx, brandName)
	} else {
		r0 = ret.Get(0).(brand.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, brandName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, brandDomain
func (_m *Repository) Store(ctx context.Context, brandDomain *brand.Domain) (brand.Domain, error) {
	ret := _m.Called(ctx, brandDomain)

	var r0 brand.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *brand.Domain) brand.Domain); ok {
		r0 = rf(ctx, brandDomain)
	} else {
		r0 = ret.Get(0).(brand.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *brand.Domain) error); ok {
		r1 = rf(ctx, brandDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
