// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	brand "shoe-store/domains/brand"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *Usecase) GetAll(ctx context.Context) ([]brand.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []brand.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []brand.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]brand.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Usecase) GetByID(ctx context.Context, id int) (brand.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 brand.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) brand.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(brand.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, brandDomain
func (_m *Usecase) Store(ctx context.Context, brandDomain *brand.Domain) (brand.Domain, error) {
	ret := _m.Called(ctx, brandDomain)

	var r0 brand.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *brand.Domain) brand.Domain); ok {
		r0 = rf(ctx, brandDomain)
	} else {
		r0 = ret.Get(0).(brand.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *brand.Domain) error); ok {
		r1 = rf(ctx, brandDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
